#\u670D\u52A1\u7AEF\u53E3
server:
  port: 9092

#\u670D\u52A1\u540D\u79F0
spring:
  profiles:
    active: dev
  application:
    name: diana-gateway
  cloud:
    config:
      profile: dev,test,prod
      discovery:
        enabled: true
        serviceId: diana-gateway
    gateway:
      routes: #\u8DEF\u7531\u89C4\u5219
      - id: oreder-service  #\u8BA2\u5355
        uri: http://localhost:8081
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1

#\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
